const dataRecentApplicant = [
  {
    id: 1,
    logo: "https://asset-a.grid.id/crop/0x106:1080x1053/700x0/photo/2019/12/04/3984547798.jpg",
    applicantName: "John Doe",
    jobTitle: "Full Stack Developer",
    skills: ["React.js"],
    uploadDate: "October 20, 2023",
  },
  {
    id: 2,
    logo: "https://xbvpvpptidao.cdn.shift8web.ca/wp-content/uploads/2023/02/visa-indonesia-untuk-orang-india-768x512.jpg",
    applicantName: "Jane Smith",
    jobTitle: "UX/UI Designer",
    skills: ["UI/UX Design"],
    uploadDate: "October 19, 2023",
  },
  {
    id: 3,
    logo: "https://img.okezone.com/content/2018/06/26/406/1914217/cara-paling-gampang-memotret-orang-yang-tampil-di-atas-panggung-UseMzQHALe.jpg",
    applicantName: "Bob Johnson",
    jobTitle: "Data Scientist",
    skills: ["Python"],
    uploadDate: "October 18, 2023",
  },
  {
    id: 4,
    logo: "https://media.suara.com/pictures/653x366/2022/11/06/27140-open-minded-freepik.jpg",
    applicantName: "Alice Johnson",
    jobTitle: "Mobile App Developer",
    skills: ["React Native"],
    uploadDate: "October 17, 2023",
  },
  {
    id: 5,
    logo: "https://radarmukomuko.disway.id/upload/ae8cce2300da0e078c20e7750caf0dd1.jpg",
    applicantName: "Charlie Brown",
    jobTitle: "Backend Developer",
    skills: ["Node.js"],
    uploadDate: "October 16, 2023",
  },
  {
    id: 6,
    logo: "https://cdn-image.hipwee.com/wp-content/uploads/2018/10/hipwee-photo-1538291388330-14f5cb8a6ddf-640x427.jpg",
    applicantName: "Eva Davis",
    jobTitle: "Graphic Designer",
    skills: ["Editing, Illustration"],
    uploadDate: "October 15, 2023",
  },
  {
    id: 7,
    logo: "https://example.com/logo7.png",
    applicantName: "George Wilson",
    jobTitle: "Network Engineer",
    skills: ["Cisco"],
    uploadDate: "October 14, 2023",
  },
  {
    id: 8,
    logo: "https://example.com/logo8.png",
    applicantName: "Helen Martinez",
    jobTitle: "DevOps Engineer",
    skills: ["Docker"],
    uploadDate: "October 13, 2023",
  },
  {
    id: 9,
    logo: "https://img.idxchannel.com/media/700/images/idx/2023/04/08/Artis_Korea_Terkaya_2023.jpg",
    applicantName: "Ivan Kim",
    jobTitle: "Quality Assurance Tester",
    skills: ["Automated Testing"],
    uploadDate: "October 12, 2023",
  },
];

export default dataRecentApplicant;
