const jobData = [
  {
    id: 1,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/LinkAja.svg/2048px-LinkAja.svg.png",
    jobTitle: "Front End Developer",
    companyName: "LinkAja",
    location: "Jakarta",
    postDate: "October 15, 2023",
    description: "We are actively seeking a skilled Front End Developer to join our growing team at LinkAja. As a Front End Developer, you will be responsible for implementing visual elements that users see and interact with in our web applications, ensuring a seamless and engaging user experience. The ideal candidate should have a solid understanding of React.js and a strong grasp of HTML/CSS. Join us in Jakarta, Indonesia, and contribute to building innovative digital solutions in a dynamic and collaborative environment.",
    requirements: [
      "Experience in front-end development",
      "Expertise in React.js",
      "Strong HTML/CSS knowledge",
      "Strong problem-solving skills",
      "Ability to work collaboratively in a team",
      "Excellent communication skills",
      "Up-to-date with the latest industry trends",
    ],
    jobType: "Full-time",
  },
  {
    id: 2,
    logo: "https://1000logos.net/wp-content/uploads/2021/12/Telkomsel-logo.png",
    jobTitle: "Data Scientist",
    companyName: "Telkomsel",
    location: "Bandung",
    postDate: "October 15, 2023",
    description: "Telkomsel is looking for an experienced Data Scientist to join our innovative team in Bandung, Indonesia. In this role, you will play a key part in leveraging data analytics and machine learning to extract valuable insights. The successful candidate should possess expertise in data analysis, machine learning, and proficiency in Python. If you are passionate about transforming data into actionable intelligence, join Telkomsel and contribute to shaping the future of data-driven decisions.",
    requirements: [
      "Experience in data analysis",
      "Machine learning expertise",
      "Python proficiency",
      "Strong analytical and problem-solving skills",
      "Ability to interpret and communicate complex findings",
      "Attention to detail",
      "Team player with excellent interpersonal skills",
    ],
    jobType: "Contract",
  },
  {
    id: 3,
    logo: "https://signature.mdmedia.co.id/uploads/app/6NZfq7v",
    jobTitle: "UI/UX Designer",
    companyName: "Bukalapak",
    location: "Surabaya",
    postDate: "October 15, 2023",
    description: "Bukalapak is on the lookout for talented UI/UX Designers to join our creative team in Surabaya, Indonesia. As a UI/UX Designer, you will be involved in crafting visually stunning and user-friendly interfaces. The ideal candidate should have experience in UI/UX design, proficiency in Adobe XD, and a creative mindset. Join us and be part of creating exceptional digital experiences for millions of users.",
    requirements: [
      "Experience in UI/UX design",
      "Proficiency in Adobe XD",
      "Creative mindset",
      "Excellent design portfolio showcasing previous work",
      "Understanding of user-centered design principles",
      "Ability to iterate designs and solutions efficiently",
      "Collaborative and open to feedback",
    ],
    jobType: "Part-time",
  },
  {
    id: 4,
    logo: "https://www.telkom.co.id/data/image_upload/page/1594108255409_compress_logo%20telkom%20indonesia.png",
    jobTitle: "Back End Developer",
    companyName: "Telkom Indonesia",
    location: "Yogyakarta",
    postDate: "October 15, 2023",
    description: "Telkom Indonesia is expanding its team and opening a position for an experienced Back End Developer in Yogyakarta, Indonesia. As a Back End Developer, you will be responsible for server-side application logic and integrating the work of front-end developers. The ideal candidate should have experience in backend development, expertise in Node.js, and strong database management skills. If you are passionate about building robust and scalable backend solutions, join us on this exciting journey.",
    requirements: [
      "Experience in backend development",
      "Node.js expertise",
      "Database management skills",
      "Knowledge of RESTful API design and implementation",
      "Familiarity with cloud platforms (e.g., AWS, GCP)",
      "Strong problem-solving and debugging skills",
      "Ability to work in an agile development environment",
    ],
    jobType: "Project-based",
  },
  {
    id: 5,
    logo: "https://www.soocaphoto.com/wp-content/uploads/2022/10/PT-Infomedia-Nusantara-Logo.png",
    jobTitle: "Graphic Designer",
    companyName: "Infomedia Nusantara",
    location: "Semarang",
    postDate: "October 15, 2023",
    description: "Infomedia Nusantara is offering an exciting opportunity for a talented Graphic Designer to join our creative team in Semarang, Indonesia. As a Graphic Designer, you will play a crucial role in creating visual concepts to communicate ideas that inspire and captivate our audience. The ideal candidate should have experience in graphic design, proficiency in Adobe Creative Suite, and a keen attention to detail. If you are passionate about visual storytelling and creativity, join us and contribute to building impactful design solutions.",
    requirements: [
      "Experience in graphic design",
      "Proficiency in Adobe Creative Suite",
      "Attention to detail",
      "Strong creative and conceptual thinking",
      "Ability to work on multiple projects simultaneously",
      "Excellent time management skills",
      "Collaborative mindset with a proactive approach",
    ],
    jobType: "Apprenticeship",
  },
];

export default jobData;
